name: learning_shop_bloc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  flutter_screenutil:
  dots_indicator:
  intl:
  gap:
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.2
  cloud_firestore: ^4.15.2


  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
